### ISSUE TITLE
Беда с прошедшим временем, кое-где с причастиями

### ISSUE THREAD

**Issue by dash-po** [kbogatyrev/Test#141]
В прошедшем времени беда (-асо, аси): ~~найтись~~, ~~прийтись~~, ~~обойтись~~, ~~пройтись~~, ~~срастись~~, ~~честь~~, ~~выесть~~,~~затолочь~~ и др., ~~разреветься~~, ~~зашибиться~~, ~~зыбиться~~, ~~зиждиться~~, ~~заесться~~, ~~объесться~~, ~~жечься~~, ~~зажечься~~ и пр., ~~толочься~~, ~~затолочься~~, ~~перетолочься~~, ~~зайти~~

Беда с прошедшим временем и причастиями: **завестись**, **плестись**, **заплестись, поплестись, проплестись, сплестись**, ~~зачесться (не должно быть причастий)~~, ~~обчесться, счесться~~, ~~забыться, забыться (сбы́вшисься)~~, ~~перейти~~, ~~прейти~~, **прийти**, ~~обойти~~, ~~подойти~~, ~~взойти~~

**Comment by kbogatyrev** [comment]
Fixed in 4.1.1.x

**Comment by kbogatyrev** [comment]
Я бы не сказал, что fixed, половина не работает :(

**Comment by kbogatyrev** [comment]
плестись вынесено в отдельную запись.
