### ISSUE TITLE
Дошедши-дойдя

### ISSUE THREAD

**Issue by dash-po** [kbogatyrev/Test#159]
сменилась норма (или употребление) и нужно вписать ДВА ВАРИАНТА везде, где это необходимо... нашедши-найдя и пр.

**Comment by kbogatyrev** [comment]
Еще глаголы, у которых в базе данных возможно пропущена помета (9):
~перейти~
~(прейти)~
~прийти~
~обойти~
~войти~
~дойти~
~превзойти~
~изойти~
~низойти~
~снизойти~
~произойти~
~пойти~
~сойти~
~отойти~
~уйти~
~выйти~
