### ISSUE TITLE
Склонение

### ISSUE THREAD

**Issue by kbogatyrev** [kbogatyrev/Test#17]
СУБСТАНТИВНОЕ СКЛОНЕНИЕ

РЕГУЛЯРНЫЕ ФОРМЫ

1. ~~1аº~~ ~~В~~ ~~существительных~~ ~~мужского рода на –анин, в тех, у которых ударение должно стоять на ИН~~, ~~а именно: АРМЯНИН, СЛАВЯНИН, СЕЛЯНИН, ДВОРЯНИН~~ – ~~неверно проставлено ударение на Я по всей парадигме~~. 
2.	~~В парадигме слова ГОСПОДИН неверно стоит ударение на О в единственном числе: госпОдин~~
3.	~~У РАЗ слишком много лишних окон открывается~~ Так и должно быть: 4 окна по одному на каждую часть речи (это вопрос отображения, программа, показывающая формы, создает отдельное окно для каждой части речи).
4.	~~МАДЬЯР – нет варианта родительного падежа~~ КБ: мадьяр	мо	1a(2), так что родительный падеж должен быть мадьяр (или я чего-то не понял)?
5.	у слов с пометой 4f ~~ВОЖЖА~~, ~~СВЕЧА~~, ~~ВОЖЖИ~~ – пустая парадигма
6.	у слов с пометой 1f – ~~ГУБА~~, ~~ЖЕЛЕЗА~~, ~~СЛЕЗА~~, ~~ЩЕПА~~, ~~ПРОСВИРА~~, ~~ПРОСФОРА~~, ~~СЛОБОДА~~, ~~ГВОЗДЬ~~, ~~КОН~~Ь – пустая парадигма
7.	у слов с пометой 2f – ~~НОЗДРЯ~~, ~~НОЗДРИ~~, ~~ЧЕРВЬ~~ – пустая парадигма, ~~у слова ПРОСТЫНЯ есть лишь форма GEN PL~~
8.	у ~~БОРОНА~~ словарь дает вариант 1f//1f’ – а программа выдает только одно окно, так и надо?
9.	~~у ДЕРЕВЦЕ – нет форм единственного числа~~
10.	~~у слов с пометой 3а 1 и 2 в кружочках, а также со звездочкой: ДРЕВКО, ЛИЧИКО, ПЛЕЧИКО, КОЛЁСИКО – нет формы GEN PL~~
11.	У слов, у которых стоит в словаре помета «0» либо пустые, либо нерабочие окна: ~~ЗАМДИРЕКТОРА~~, ~~ЗАВТРА, ЗАММИНИСТРА, ЗКСТРА, ХАУСА, ультра~~ и пр.

**Comment by dash-po** [comment]
пункты 5. 6. 7. 11. - проблем больше нет
ВОЖЖА - иного характера проблема, там пустая парадигма
