### ISSUE TITLE
зацвести

### ISSUE THREAD

**Issue by dash-po** [kbogatyrev/Test#286]
должно быть зацветший, а написано зацвётший

**Comment by kbogatyrev** [comment]
~~придется исправить вручную~~

**Comment by kbogatyrev** [comment]
Trailing comment: но прич. прош. зацветший

**Comment by kbogatyrev** [comment]
бредший, ведший, забредший, заведший, зацветший, истекший, нарекший(ся), небрегший, обретший(ся), побредший, пренебрегший, проистекший, разбредшийся, цветший

**Comment by kbogatyrev** [comment]
d9263324a781b18dfb21d6cae80598b0e517262c
