### ISSUE TITLE
Часто отсутствует 3 Pl

### ISSUE THREAD

**Issue by kbogatyrev** [kbogatyrev/Test#99]

**Comment by kbogatyrev** [comment]
Даша, добавьте, пожалуйста, примеры.

**Comment by dash-po** [comment]
Здравствуйте, Константин!
Я совсем не забыла о том, что должна добавить примеры - просто у меня опять
сломался компьютер - начал переустанавливать windows и завис, показывает
ошибку. Поэтому я третий день без своих материалов, которые сначала
заносила в ворд-файл:( но я наверное могу достать  примеры из того, что Вам
отправляла почтой - не понимаю, почему не догадалась раньше. Если не
сегодня, то завтра всё сделаю.

С уважением, Даша

2018-01-26 17:04 GMT+03:00 Konstantin Bogatyrev <notifications@github.com>:

**Comment by kbogatyrev** [comment]
Даша, здравствуйте!
Это было не напоминание, я просто наводил порядок в Гитхабе, помечал кто за что отвечает. 
Я тем временем нашел кое-какие серьезные ошибки, пере-проверяя присланный Вами файл. Расскажу подробнее при случае.
Постараюсь связаться с Вами на выходных.
К


    On Friday, January 26, 2018, 6:52:53 AM PST, dash-po <notifications@github.com> wrote:  
 
 Здравствуйте, Константин!
Я совсем не забыла о том, что должна добавить примеры - просто у меня опять
сломался компьютер - начал переустанавливать windows и завис, показывает
ошибку. Поэтому я третий день без своих материалов, которые сначала
заносила в ворд-файл:( но я наверное могу достать примеры из того, что Вам
отправляла почтой - не понимаю, почему не догадалась раньше. Если не
сегодня, то завтра всё сделаю.

С уважением, Даша

2018-01-26 17:04 GMT+03:00 Konstantin Bogatyrev <notifications@github.com>:

**Comment by dash-po** [comment]
Хорошо! Спасибо большое! Надеюсь, Кот к тому времени излечит мой компьютер)

26 января 2018 г., 17:57 пользователь Konstantin Bogatyrev <
notifications@github.com> написал:

> Даша, здравствуйте!
> Это было не напоминание, я просто наводил порядок в Гитхабе, помечал кто
> за что отвечает.
> Я тем временем нашел кое-какие серьезные ошибки, пере-проверяя присланный
> Вами файл. Расскажу подробнее при случае.
> Постараюсь связаться с Вами на выходных.
> К
>
>
> On Friday, January 26, 2018, 6:52:53 AM PST, dash-po <

**Comment by dash-po** [comment]
Вот лишь маленькая часть:

Нет 3 лица множественного числа: 

Быть
Забыть
Подзабыть и др
Внимать
Принимать
Выдрать
Живописать
заехать
Вызваться
Обязываться
Выбраться
Выдраться
Проехаться и от него приставочные
Зыбиться
Бриться
Ссесться
Забыться
Сбыться
